name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          # host: 143.42.45.16
          # username: root
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          host: 157.245.115.51
          username: root
          password: 1@Samtonia
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            
            # Optionally, specify the Node version to use
            nvm use v20.11.1

            cd Samtonia
            git pull 
            /root/.nvm/versions/node/v20.11.1/bin/yarn install --frozen-lockfile
            /root/.nvm/versions/node/v20.11.1/bin/yarn build
            /root/.nvm/versions/node/v20.11.1/bin/pm2 stop all
            pwd
            cd .github
            /root/.nvm/versions/node/v20.11.1/bin/pm2 start ecosystem.config.js
