name: Samtonia Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Install PM2 globally
      run: npm install -g pm2

    - name: Start application with PM2
      run: pm2 start ecosystem.config.js --env production


    - name: Save PM2 process list
      run: pm2 save

    - name: Setup PM2 to restart on reboot
      run: pm2 startup
